#!/usr/bin/env bash
# this will read and cut from a file

filename="/etc/passwd"

while IFS=":" read -r username _ userid _ _ homedir _
do
    echo "$username"
    echo "$userid"
    echo "$homedir"
done < "$filename"

