#!/usr/bin/env bash
# this will write the story of password

filename="/etc/passwd"

while IFS=":" read -r username _ userid groupid _ homedir shell
do
    read -r -a userinfo <<< $(getent passwd "$username")
    passcode=${userinfo[1]}
    info=${userinfo[4]}
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode $passcode, more info about the user here: $info"
done < "$filename"

