#!/usr/bin/env bash
# This will check if a file exist and it will check the content in it
if [ -e "school" ]
then
	echo "school file exist"
	if [ -s "school" ]
       	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
       	then
        	echo "school is a regular file"
	fi
else
	echo "school file is not empty"
fi
