#!/usr/bin/env bash
# This will check if a file exist and it will check the content in it
filename="school"
if [ -e $filename ]
then
	echo "school file exist"
	if [ -s $filename ]
       	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f $filename ]
       	then
        	echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
