#!/usr/bin/env bash
# this will change my local host and facebook host on my host
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 	localhost" > ~/host.new
echo "8.8.8.8 		facebook.com" >> ~/host.new
cp -f ~/hosts.new /etc/hosts
